name: CI

on:
  push:
    branches:
      - "*"
  pull_request:

  # Allow running manually
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn install

      - name: Spellcheck
        run: yarn run cspell

  lint_filenames:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Lint filenames
        run: python ./scripts/lint-filenames.py

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: bash ./scripts/setup.sh

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install
        run: yarn install

      - name: Build newsletters
        run: bash ./scripts/render-all.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    needs:
      - spellcheck
      - build
      - lint_filenames

    if: github.ref_name == 'master'

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
